name: Install AWS SAM CLI

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  install-sam-cli:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run make init
        run: make init