name: test

on:
  workflow_dispatch:

jobs:
  python-integration:
    runs-on: windows-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      SAM_CLI_DEV: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: 'python.exe -c "import pip; print(pip.__version__)"'
      - run: "make init"
      - run: "pytest tests/integration/buildcmd/test_build_cmd.py::TestBuildCommand_PythonFunctions_WithoutDocker_2_template_yaml::test_with_default_requirements -vv"
